[server]
enableStaticServing = true

[theme]
font = "IBM Plex Sans, sans-serif"

[[theme.fontFaces]]
family = "IBM Plex Sans"
url = "app/static/fonts/IBMPlexSans-Light.woff2"
weight = "300"

[[theme.fontFaces]]
family = "IBM Plex Sans"
url = "app/static/fonts/IBMPlexSans-Regular.woff2"
weight = "400"

[[theme.fontFaces]]
family = "IBM Plex Sans"
url = "app/static/fonts/IBMPlexSans-SemiBold.woff2"
weight = "600"
